<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Wyrd.Ecs.Persistence.Continuous</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <IsAotCompatible>true</IsAotCompatible>
    <IsPackable>true</IsPackable>
    <Version>0.1.0-alpha</Version>
    <Description>Continuous write-ahead-log persistence for Wyrd.Ecs.</Description>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Wyrd.Ecs.Persistence.Continuous.Tests" />
    <InternalsVisibleTo Include="Wyrd.Ecs.Benchmarks" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\..\..\README.md" Pack="true" PackagePath="\" Visible="false" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Core\Wyrd.Ecs\Wyrd.Ecs.csproj" />
    <ProjectReference Include="..\..\Wyrd.Ecs.Persistence\Wyrd.Ecs.Persistence.csproj" />
  </ItemGroup>

</Project>
