<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Wyrd.Ecs.Benchmarks</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.14.0" />
    <PackageReference Include="Friflo.Engine.ECS" Version="3.6.0" />
    <PackageReference Include="fennecs" Version="0.6.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Core\Wyrd.Ecs\Wyrd.Ecs.csproj" />
    <ProjectReference Include="..\..\src\Persistence\Wyrd.Ecs.Persistence\Wyrd.Ecs.Persistence.csproj" />
    <ProjectReference Include="..\..\src\Persistence\Continuous\Wyrd.Ecs.Persistence.Continuous\Wyrd.Ecs.Persistence.Continuous.csproj" />
    <ProjectReference Include="..\..\src\Persistence\Binary\Wyrd.Ecs.Persistence.Binary\Wyrd.Ecs.Persistence.Binary.csproj" />
    <ProjectReference Include="..\..\src\Persistence\Binary\Wyrd.Ecs.Persistence.Binary.Generators\Wyrd.Ecs.Persistence.Binary.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" PrivateAssets="all" />
    <ProjectReference Include="..\..\src\Persistence\Wyrd.Ecs.Persistence.Generators\Wyrd.Ecs.Persistence.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" PrivateAssets="all" />
    <ProjectReference Include="..\..\src\Core\Wyrd.Ecs.Generators\Wyrd.Ecs.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" PrivateAssets="all" />
  </ItemGroup>

</Project>
