<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Wyrd.Ecs.Persistence.Continuous</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Wyrd.Ecs.Persistence.Continuous.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Wyrd.Ecs\Wyrd.Ecs.csproj" />
    <ProjectReference Include="..\Wyrd.Ecs.Persistence\Wyrd.Ecs.Persistence.csproj" />
  </ItemGroup>

</Project>
